language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t chen572/docker-react-test -f Dockerfile.dev .

script:
  - docker run -e CI=true chen572/docker-react-test npm run test

deploy:
  provide: elasticbeanstalk
  region: "eu-central-1"
  app: "docker-react-test"
  env: "DockerReactTest-env"
  bucket_name: "elasticbeanstalk-eu-central-1-562669185924"
  bucket_path: "docker-react-test"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY